name: PF2e Inline Traits CD

on:
  workflow_dispatch:
    branches: [release]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Update Manifest
        run: |
          MODULE_VERSION=$(grep -oP '(?<="version": ")[^"]+' dist/module.json | tr -d '\n')
          echo "moduleVersion=$MODULE_VERSION" >> $GITHUB_ENV
          perl -pi -e 's/(?<="version": )"([^"]+)"/"$1.$ENV{GITHUB_RUN_NUMBER}"/' dist/module.json

      - name: Zip Files
        working-directory: ./dist
        run: zip -r ./pf2e-inline-traits.zip ./*

      - name: Create Version Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.moduleVersion }}.${{ github.run_number }}
          allowUpdates: false
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dist/module.json,./dist/pf2e-inline-traits.zip'
          tag: ${{ env.moduleVersion }}.${{ github.run_number }}

      - name: Create Latest Release
        id: create_latest_release
        uses: ncipollo/release-action@v1
        with:
          name: Latest
          allowUpdates: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dist/module.json,./dist/pf2e-inline.traits.zip'
          tag: latest
